### ISSUE TITLE
Square operation missing

### ISSUE THREAD

**Issue by davidrs06** [libDirectional/libDirectional#3]
Hi ! From the "Random sampling from the watson distribution" paper, it seems that U_1 term in step 3 is squared, while your implementation just uses [U_1](https://github.com/libDirectional/libDirectional/blob/master/lib/distributions/Hypersphere/WatsonDistribution.m#L96) as is.

Is this a typo in your implementation or in the paper ?

Cheers,
David

**Comment by FlorianPfaff** [comment]
Hi and thanks for your report!
I implemented this a while ago and just took another look at it. In some functions of our library, we did fix bugs that were present in the respective papers - however, since I cannot remember fixing a bug in this specific routine, I believe that this was simply a typo. The results in cases we tested were very similar, which explains why did not notice this bug.

You can download the fixed version now. I also spotted a part of step 7 that was unnecessarily complex in the original paper, which I have now simplified in the code. You're welcome to test and further comment. And we'd also welcome you to get in touch with us and tell us what you use the library for (we're not after money, just curious!).

Greetings,

Florian

**Comment by davidrs06** [comment]
Great, I'll have a look in the next weeks, thanks for the quick reply :)
