### ISSUE TITLE
ToroidalMixture parameter estimation

### ISSUE THREAD

**Issue by hrheydarian** [libDirectional/libDirectional#8]
Hi,

I have a dataset which seems to have a ToroidalMixture distribution or other mixture-like circular distributions.

Would it be possible to estimate the parameters of a ToroidalMixture (or other circular-mixture distributions) for this data?
I can see in your package examples for estimating parameters of WNDistribution from data but for mixtures it seems that there is no estimation routine. Is that correct?

Thanks in advance,
Hamidreza

**Comment by FlorianPfaff** [comment]
Hi,
if you want to obtain a pdf based on your samples: I have added the capability to determine parameters of a multidimensional Fourier series (HypertoroidalFourierDistribution) based on samples. The change will be pushed to this repository soon. 
Small example how you can use it:
```
noCoeffPerDim=7;
samples = [ToroidalWNDistribution([1;1],0.3*[1,0.7;0.7,1]).sample(1000),...
    ToroidalWNDistribution([4;4],0.3*[1,-0.3;-0.3,1]).sample(1000)];
wd = HypertoroidalWDDistribution(samples);
figure(1), wd.plot;
hfd = HypertoroidalFourierDistribution.fromDistribution(wd, [noCoeffPerDim, noCoeffPerDim], 'identity');
figure(2), hfd.plot;
```
Of course, you just use your samples instead of generating them as in the example. Choose noCoeffsPerDim wisely. Low values result in a smooth density, that, however, has little power to approximate complicated densities. High values can result in a distribution that is more "peaky" than you may desire. This is because, in essence, you can never know for sure how the density that generated the samples may look like. If you only have samples, then even a distribution that only has probability mass on these points may actually be plausible (although this is rarely the desired solution).
Hope it helps.

Greetings,
Florian

**Comment by FlorianPfaff** [comment]
If there is no further need for discussion, I think this issue can be closed.
